apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: gaiagpu-scheduler
extenders:
- urlPrefix: http://127.0.0.1:32767/gaiagpu-scheduler
  filterVerb: predicates
  enableHTTPS: false
  nodeCacheCapable: false
  ignorable: false
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf